# Generated by Django 4.0.5 on 2022-06-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0004_markasamochodu_wlasciciel_samochody_paliwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochody',
            name='wlasciciele',
            field=models.ManyToManyField(related_name='samochody', to='samochody.wlasciciel'),
        ),
    ]
